#cloud-config

bootcmd:
  - DEBIAN_FRONTEND=noninteractive apt-get -yq update

apt:
  conf: |
    APT {
      Get {
        Assume-Yes "true";
        Fix-Broken "true";
      };
    };

packages:
  - geoipupdate
  - git
  - python3-venv
  - unattended-upgrades
package_upgrade: true

runcmd:
  - echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
  - DEBIAN_FRONTEND=noninteractive dpkg-reconfigure unattended-upgrades
  - mkdir /usr/share/GeoIP
  - echo "AccountID ${maxmind_account_id}" > /etc/GeoIP.conf
  - echo "LicenseKey ${maxmind_licence_key}" >> /etc/GeoIP.conf
  - echo "EditionIDs GeoIP2-Country GeoIP2-City" >> /etc/GeoIP.conf
  - geoipupdate -d /usr/share/GeoIP
  - chown ubuntu:ubuntu /home/ubuntu /home/ubuntu/start.sh /home/ubuntu/config.yaml
  - sleep 5 && sudo -u ubuntu /bin/bash /home/ubuntu/start.sh

write_files:
  - content: ${app_config}
    path: /home/ubuntu/config.yaml
    owner: root:root
    permissions: '0600'
  - content: ${crontab}
    path: /etc/cron.d/redirector
    owner: root:root
    permissions: '0644'
  - content: ${start_script}
    path: /home/ubuntu/start.sh
    owner: root:root
    permissions: '0644'
